### ISSUE TITLE
pcsync pullAll returns different results

### ISSUE THREAD

**Issue by yorschor** [playcanvas/playcanvas-sync#10]
pcsync pullAll shows the same problems as diffAll #9 . Pulling results sometimes in the correct hierarchy and sometimes in a complete mess of duplicate files in the root and more.
I have for now memorized what files should be present at the bottom of the shown list and then only say yes to the pull. This works areoudn every 3 times. (Pull -> see if its correct. If not delete local files -> try again)

**Comment by zachpeterpaul** [comment]
Please double-check that the capitalization in your sync config file is correct/matches your file system. Also pcsync uses third party modules to listen to low level os events, and those modules may have limitations for certain os’s. In the worst case you may have to settle for a modified/simplified workflow. Only pull and pullAll can change local files (pcwatch can't). One can, for instance, have a workflow that only uses push/pushAll, and pcwatch (if it's working on your os).

**Comment by zachpeterpaul** [comment]
All should now work correctly, please try the latest version of playcanvas-sync

**Comment by willeastcott** [comment]
Closing since `pcwatch` now works on Windows. Please reopen if you continue to experience problems with this.
