### ISSUE TITLE
Add .js.map to textual types

### ISSUE THREAD

**Issue by detzt** [playcanvas/playcanvas-sync#13]
I would like to sync the *.js.map files as well.
Since they are not recognized as textual files, I cannot add them with `ignore_all_files_with_extension` either.

**Comment by detzt** [comment]
After uploading the file manually, I noticed that PlayCanvas itself treats .js.map files as binary and prints the error message "Error loading binary resource: build.js.map [InvalidStateError: responseText is only available if responseType is '' or 'text'.]"

**Comment by yaustar** [comment]
Side note on adding it manually, rename it to .txt, upload and rename to .map.

**Comment by detzt** [comment]
Thanks for the hint. I already tried this with .txt and .json, but then the file is treated as an Asset and is not reachable at the path referenced in the corresponding .js file.
When I create it manually as a .js file and then rename to .js.map it complains that the json content is apparently not valid js.
Now I wonder whether PlayCanvas supports .js.map files or if this should be an issue in that repo 🤔

**Comment by yaustar** [comment]
Oh yes. You may be best off embedding the sourcemap into the build.js/output.js file rather than a .map as the folder structure you see in PlayCanvas isn't how it's laid out on the server. Each asset on the server is in it's own folder, including the script assets so relative paths don't work.

**Comment by detzt** [comment]
Thanks for pointing me in that direction, I didn't know source maps can be embedded.
For anyone with the same issue: I needed to set both `inlineSourceMap` and `inlineSources` in the `tsconfig.json` for this to work.

**Comment by detzt** [comment]
I'm closing this now as this is not relevant until PlayCanvas supports .js.map files.
