### ISSUE TITLE
Option to disable confirmation prompt

### ISSUE THREAD

**Issue by detzt** [playcanvas/playcanvas-sync#14]
I am trying to automate `pcsync pushAll` as a workaround while `pcwatch` is not working on Windows.
So far I've managed to call `pcsync pushAll` automatically, but I still need to confirm the upload with "y" every time.
It would be great to provide an option to skip the confirmation like `-y` or` --headless`.

**Comment by detzt** [comment]
If you agree with that feature and tell me which parameter you would like, I am willing to implement it and create a PR :)

**Comment by zachpeterpaul** [comment]
pcwatch should now work on Windows, please try the latest version of playcanvas-sync

**Comment by willeastcott** [comment]
Closing since `pcwatch` now works on Windows. Please reopen if you continue to experience problems with this.
