### ISSUE TITLE
Unable to run in CI environment as --yes/ -y is not supported.

### ISSUE THREAD

**Issue by nyan-left** [playcanvas/playcanvas-sync#18]
Hello,

I'm currently using a fork of this repo which skips the `pushAll` confirmations to deploy in CI.
Wondering if you would be happy to accept a PR which adds --yes/-y flags to accept all confirmations? 

Thanks :)

**Comment by willeastcott** [comment]
Hi @nyan-left - sure, we love PRs! 😄  @zachpeterpaul looks after this repo - he can help you get it in a mergeable state.

**Comment by nyan-left** [comment]
That's great to hear :)

Hi @zachpeterpaul,
I've sent through #19, plese let me know if you would like any changes to it.

Thanks!

**Comment by zachpeterpaul** [comment]
This has been implemented
