### ISSUE TITLE
Where to put the target directory??

### ISSUE THREAD

**Issue by tidus2020** [playcanvas/playcanvas-sync#22]
Error: could not find target directory: . Check capitalization.

I put .pcconfig in the playcanvas-sync-master folder, and set "PLAYCANVAS_TARGET_DIR": "/project"

And run node pcwatch.js diffAll

**Comment by Christopher-Hayes** [comment]
Hey @tidus2020 I am also getting that error. The error seems to show if you don't have a `.pcconfig` config file in your home directory. In your case, you put the `.pcconfig` in your repo folder. If you move that config file to your home directory, I expect the error would be fixed.

**Comment by yaustar** [comment]
Yes, the `.pcconfig` has to have at least the target directory so that playcanvas-sync knows where to find the rest of the settings

**Comment by tfsJoe** [comment]
It seems odd that .pcconfig has to be in the home directory. Ultimately, this fixed my problem as well. However, I would want to be able to store the project ID and branch ID inside my project, I would think, in case I want to work on more than one PlayCanvas project on the same computer.

I have seen some comments elsewhere that using `"PLAYCANVAS_USE_CWD_AS_TARGET": 1` makes it easier to work on multiple projects; this seems true, except that having to change the project ID in the home directory every time you switch projects seems counterintuitive.

I tried only putting the API key and other general settings in the home copy of .pcconfig, and putting project specific settings inside the project directory, but then it complained: "Missing config variable: PLAYCANVAS_PROJECT_ID"

I believe it would make sense to merge these when running and then complain only if it's missing afterward. Is there a reason not to support this? I would be willing to make a PR if the direction sounds OK.
