### ISSUE TITLE
Write a step by step tutorial on setting up a simple workflow

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-sync#7]
Users are confused on what to write or where to put config files, especially on Windows.

Writing a getting started doc with lots of images would really help.

**Comment by Pandan** [comment]
It would also be great with some type of example project.

**Comment by yaustar** [comment]
This should also include a TypeScript example folder structure setup and also where to find the API key.

**Comment by yaustar** [comment]
This has been done here: https://github.com/playcanvas/playcanvas-sync/blob/master/step-by-step-guide.md
