### ISSUE TITLE
Sync is kinda broken. (Company Project)

### ISSUE THREAD

**Issue by yorschor** [playcanvas/playcanvas-sync#8]
Hi. 
I know this kinda general. I´ll become more specific if needed. 
I have been using PC Sync on a company project with my personal API token for around one week now. 
These are some of the issues I have run into. 

* "pcsync diffAll" returns different results. More often than not it shows files missing on local that are already downloaded. I circle through the different results until i see one that I know is correct. -> Then only I use pcwatch

* pcsync pullAll shows the same problems as diffAll. Pulling results sometimes in the correct hierarchy and sometimes in a complete mess of duplicate files in the root and more. I have for now memorized what files should be present at the bottom of the shown list and then only say yes to the pull. 

* pcwatch sometimes corrupts files. I had this happen 3 times by now. the pcwatch console shows some kind of  "UnhandledPromiseRejectionWarning" or similar. Following saves to the local file will no longer sync. In the online editor the file is no longer able to open and must be deleted and then created again copy pasting the old code in there. Doesn't happen often still a problem :/ 

* pcwatch once duplicated the ammo folder and its scripts as well as 3 other script files in various places. The console output showed pcwatch updating seemingly random files every second without me changing the file. This only happend once to me. Still a bit scary ^^

I hope those issues can somehow be resolved. PCSync is pure bliss and I will continue to use it besides those problems. (I know how to fix them most of the time). For now my workflow is deleting all synced files locally, circling through pullAll until I see the right files. When thats done I diffAll until it shows the right result and only then start pcwatch. If that is done it mostly works fine.

If any additional information is needed I will be happy to provide :)

**Comment by willeastcott** [comment]
Thanks so much for taking the time to submit this feedback, @yorschor! We'll investigate ASAP. By the way, as a general rule of thumb, it's best to split each bug report into a separate issue. That way, we can incrementally close them as we progress.

**Comment by yorschor** [comment]
Hi. Thanks for reacting so fast. I will split the issues next time! (Or I can do it for this one now if that´s more convenient?)

**Comment by willeastcott** [comment]
Hmmm, yeah, if you could, we would appreciate it! 😄

**Comment by yorschor** [comment]
Issue Split into #9 #10 #11 #12
